server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deren-dental?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong #&allowMultiQueries=true
    hikari:
      pool-name: HikariCP
      username: root
      password: Aa9638527410!@#$%^
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: select 1

  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200

mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug

jwt:
  config:
    key: deren-dental-jwtkey-asdfqwer1234zxcv
    timeout: 604800000 #token失效时间
